CREATE TABLE [dbo].[TAB_Org_Area](
	[nid] [int] IDENTITY(1,1) NOT NULL,
	[strGUID] [varchar](50) COLLATE Chinese_PRC_CI_AS NOT NULL CONSTRAINT [DF__TAB_Org_A__strGU__267ABA7A]  DEFAULT (newid()),
	[strAreaName] [varchar](50) COLLATE Chinese_PRC_CI_AS NULL,
	[strJWDNumber] [varchar](50) COLLATE Chinese_PRC_CI_AS NULL,
 CONSTRAINT [PK_TAB_Org_Area] PRIMARY KEY CLUSTERED 
(
	[strGUID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
)


